import React, { useMemo, useState } from 'react';
import { StorageService } from '../services/storage';
import { TeamMember, AppView, WIGConfig, WIG_SETTINGS, Commitment, SurveyResult, Ticket } from '../types';
import { WHDService } from '../services/whd';
import { AIService } from '../services/ai';
import { GamificationService } from '../services/gamification';
import { getPreviousWeekId, getWeekId } from '../utils';
import UserStats from './UserStats';
import CorrelationChart from './CorrelationChart';

interface DashboardProps {
  currentUser: TeamMember;
  members: TeamMember[];
  wigConfig: WIGConfig | null;
  commitments?: Commitment[];
  tickets?: Ticket[];
  surveys?: SurveyResult[];
  surveyStartDate?: number | null;
  onNavigate: (view: AppView) => void;
}

const Dashboard: React.FC<DashboardProps> = ({
  currentUser,
  members,
  wigConfig,
  commitments = [],
  tickets = [],
  surveys = [],
  surveyStartDate,
  onNavigate,
}) => {
  // Calculate WIG Score from Survey Data
  const currentScore = useMemo(() => {
    console.log(`[Dashboard] Surveys available: ${surveys.length}`);
    let filteredSurveys = surveys;
    if (surveyStartDate) {
      filteredSurveys = surveys.filter(s => s.date >= surveyStartDate);
      console.log(`[Dashboard] Filtering by date >= ${new Date(surveyStartDate).toLocaleDateString()}. Matches: ${filteredSurveys.length}/${surveys.length}`);
    }

    if (filteredSurveys.length === 0) {
      console.log("[Dashboard] Result: No data after filtering. Falling back to default.");
      return wigConfig?.currentValue || 70;
    }

    const total = filteredSurveys.reduce((sum, s) => sum + s.average, 0);
    const avg = total / filteredSurveys.length;
    const result = Math.round(avg * 10);
    console.log(`[Dashboard] Success: Calculated ${result}% from ${filteredSurveys.length} surveys (Avg: ${avg.toFixed(2)})`);
    return result;
  }, [surveys, wigConfig, surveyStartDate]);

  const activeMembers = members.filter(m => m.id); // Valid members have an ID
  const numActive = activeMembers.length;

  const leadMeasures = wigConfig?.leadMeasures || [];

  // Get current week ID for filtering
  const currentWeekId = getWeekId();

  // Filter commitments to current week only for scorecard calculations
  const currentWeekCommitments = commitments.filter(c => c.weekId === currentWeekId);

  // Check for Missing Survey Data (Manager Only)
  const isManager = currentUser.role === 'MANAGER' || currentUser.role === 'ADMIN';
  const hasSurveyDataForWeek = useMemo(() => {
    if (!surveys || surveys.length === 0) return false;
    return surveys.some(s => s.weekId === currentWeekId);
  }, [surveys, currentWeekId]);

  // Per-member completed-commitments leaderboard (this week + all time)
  const commitmentLeaderboard = useMemo(() => {
    return (members as TeamMember[])
      .filter((m: TeamMember) => m && m.name)
      .map((m: TeamMember) => {
        const memberCommitments = (commitments as Commitment[]).filter((c: Commitment) => c.memberId === m.id);
        const thisWeek = memberCommitments.filter((c: Commitment) => c.weekId === currentWeekId && c.status === 'completed').length;
        const allTime = memberCommitments.filter((c: Commitment) => c.status === 'completed').length;
        return {
          memberId: m.id,
          name: m.name,
          avatar: m.avatar,
          streak: m.streak || 0,
          thisWeek,
          allTime,
        };
      })
      .sort((a: { allTime: number; thisWeek: number }, b: { allTime: number; thisWeek: number }) => b.allTime - a.allTime || b.thisWeek - a.thisWeek);
  }, [members, commitments, currentWeekId]);

  const handleUpdateScore = async () => {
    if (wigConfig) {
      await StorageService.updateWIGConfig({ ...wigConfig, currentValue: tempScore });
    }
    setEditingScore(false);
  };

  const handleUpdateMember = async (id: string, updates: Partial<TeamMember>) => {
    await StorageService.updateMemberMetrics(id, updates);
  };

  // AI Weekly Summary State
  const [weeklySummary, setWeeklySummary] = useState<string | null>(null);
  const [isGeneratingSummary, setIsGeneratingSummary] = useState(false);
  const [lastTicketSync, setLastTicketSync] = useState<number | null>(null);

  // Load ticket sync timestamp
  React.useEffect(() => {
    const ts = StorageService.getTicketLastSync();
    setLastTicketSync(ts);
  }, [tickets]);

  // Track whether we've already auto-generated for this week to avoid loops.
  const autoGeneratedWeekRef = React.useRef<string | null>(null);

  const handleGenerateSummary = async () => {
    setIsGeneratingSummary(true);
    console.log("Generating summary for commitments:", currentWeekCommitments.length);
    const summary = await AIService.generateWeeklySummary(currentWeekCommitments, currentWeekId);
    console.log("Received summary from AI:", summary);

    if (summary) {
      setWeeklySummary(summary);
      await StorageService.saveWeeklySummary(currentWeekId, summary);
      console.log("Summary saved to storage");
    }
    setIsGeneratingSummary(false);
  };

  // Load summary on mount or week change; auto-generate (manager-only) if none saved.
  React.useEffect(() => {
    let cancelled = false;
    const loadSummary = async () => {
      const saved = await StorageService.getWeeklySummary(currentWeekId);
      if (cancelled) return;
      if (saved) {
        setWeeklySummary(saved);
        return;
      }
      setWeeklySummary(null);
      // Auto-generate once per week, manager-only, only when there's data to summarise.
      if (
        isManager &&
        currentWeekCommitments.length > 0 &&
        autoGeneratedWeekRef.current !== currentWeekId &&
        !isGeneratingSummary
      ) {
        autoGeneratedWeekRef.current = currentWeekId;
        handleGenerateSummary();
      }
    };
    loadSummary();
    return () => { cancelled = true; };
  }, [currentWeekId, isManager, currentWeekCommitments.length]);

  return (
    <div className="space-y-10 animate-fade-in">

      {/* SECTION Zero: AI TEAM PULSE (Summary) */}
      {(weeklySummary || isManager) && (
        <div className="bg-gradient-to-r from-indigo-900 to-slate-900 rounded-2xl p-6 shadow-xl relative overflow-hidden group">
          {/* Background decoration */}
          <div className="absolute top-0 right-0 w-64 h-64 bg-white opacity-5 rounded-full blur-3xl -mr-32 -mt-32 pointer-events-none"></div>

          <div className="relative z-10">
            <div className="flex justify-between items-start mb-4">
              <div className="flex items-center gap-3">
                <div className="w-8 h-8 rounded-lg bg-white/10 flex items-center justify-center text-indigo-300">
                  <svg className="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M13 10V3L4 14h7v7l9-11h-7z" /></svg>
                </div>
                <div>
                  <h3 className="text-sm font-bold text-white uppercase tracking-wide">Weekly Team Pulse</h3>
                  <p className="text-[10px] text-indigo-200 font-medium">AI-Generated Analysis</p>
                </div>
              </div>
              {isManager && (
                <button
                  onClick={handleGenerateSummary}
                  disabled={isGeneratingSummary}
                  className="text-[10px] font-bold uppercase tracking-wider text-white/50 hover:text-white bg-white/10 hover:bg-white/20 px-3 py-1.5 rounded-lg transition-all disabled:opacity-50"
                >
                  {isGeneratingSummary ? 'Analyzing...' : (weeklySummary ? 'Regenerate' : 'Generate Analysis')}
                </button>
              )}
            </div>

            {weeklySummary ? (
              <p className="text-indigo-50 text-sm leading-relaxed font-medium animate-fade-in">
                {weeklySummary}
              </p>
            ) : (
              <div className="text-white/40 text-xs italic">
                No summary generated for this week yet.
                {isManager ? ' Click generate to analyze team performance.' : ' Check back later!'}
              </div>
            )}
          </div>
        </div>
      )}

      {/* Missing Survey Data Reminder (Managers Only) */}
      {isManager && !hasSurveyDataForWeek && (
        <div className="bg-brand-orange/10 border border-brand-orange/20 rounded-2xl p-4 flex flex-col sm:flex-row items-center justify-between gap-4 animate-fade-in">
          <div className="flex items-center gap-4">
            <div className="w-10 h-10 rounded-full bg-brand-orange/20 flex items-center justify-center text-brand-orange shrink-0">
              <svg className="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z" /></svg>
            </div>
            <div>
              <h3 className="text-sm font-bold text-slate-800 uppercase tracking-tight">Survey Data Missing</h3>
              <p className="text-xs text-slate-500 font-medium mt-0.5">No TSV uploaded for {currentWeekId}. The WIG Scoreboard relies on this data.</p>
            </div>
          </div>
          <button
            onClick={() => onNavigate(AppView.SURVEYS)}
            className="w-full sm:w-auto px-5 py-2.5 bg-brand-navy text-white text-xs font-bold uppercase tracking-wider rounded-xl hover:bg-slate-800 transition-all shadow-md hover:shadow-lg flex items-center justify-center gap-2"
          >
            <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-8l-4-4m0 0L8 8m4-4v12" /></svg>
            Upload Now
          </button>
        </div>
      )}

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
        {/* SECTION A: THE WIG (Lag Measure) */}
        <section className="lg:col-span-2 cem-card relative overflow-hidden">
          <div className="flex justify-between items-center mb-4 gap-4">
            <div className="min-w-0">
              <span className="text-[10px] font-semibold text-slate-400 uppercase tracking-widest">WIG Goal</span>
              <h2 className="text-base font-semibold text-slate-800 truncate">{wigConfig?.title || "Strategy Goal"}</h2>
              <p className="text-xs text-slate-400 mt-0.5 truncate">{wigConfig?.description || "Strategic Focus"}</p>
            </div>
            <div className="text-right shrink-0">
              <span className="text-3xl font-bold text-slate-900 tracking-tight leading-none">
                {currentScore}<span className="text-base text-slate-300 ml-0.5">%</span>
              </span>
              <div className="text-[10px] text-slate-400 font-medium mt-0.5">Target {wigConfig?.targetValue || 80}%</div>
            </div>
          </div>

          <div className="relative">
            <div className="h-2 w-full bg-slate-100 rounded-full overflow-hidden">
              <div
                className="h-full bg-gradient-to-r from-brand-red to-brand-navy transition-all duration-1000 ease-out rounded-full"
                style={{ width: `${currentScore}%` }}
              ></div>
            </div>
            <div
              className="absolute top-0 w-px h-2 bg-slate-700 opacity-30"
              style={{ left: `${wigConfig?.targetValue || 80}%` }}
            ></div>
          </div>

          {isManager && (
            <p className="text-[9px] text-slate-300 font-medium uppercase tracking-tight mt-3">
              Surveys: {surveys.length} · Start: {surveyStartDate ? new Date(surveyStartDate).toLocaleDateString() : 'None'}
            </p>
          )}
        </section>

        {/* SECTION A.5: USER STATS (Gamification v2) */}
        <section>
          <UserStats member={currentUser} />
        </section>
      </div>

      {/* SECTION B: THE SCOREBOARD (Lead Measures with Team Targets) */}
      <section className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
        {leadMeasures.map((measure, measureIndex) => {
          const teamTarget = numActive * measure.target; // TEAM TARGET = Members × Individual Target

          // CALCULATE ACTUAL: 
          // Match by ID OR by name (some commitments incorrectly store name in leadMeasureId)
          const byLeadMeasure = currentWeekCommitments.filter(c =>
            c.status === 'completed' && (
              c.leadMeasureId === measure.id ||
              c.leadMeasureId === measure.name ||
              c.leadMeasureName === measure.name
            )
          ).length;

          const totalCompleted = currentWeekCommitments.filter(c => c.status === 'completed').length;
          const hasAnyWithLeadMeasure = currentWeekCommitments.some(c => c.leadMeasureId || c.leadMeasureName);

          // If commitments have leadMeasureId, use that count; otherwise distribute total evenly
          const actual = hasAnyWithLeadMeasure
            ? byLeadMeasure
            : (measureIndex === 0 ? totalCompleted : 0);

          const percent = Math.min(100, (actual / (teamTarget || 1)) * 100);
          const isWinning = actual >= teamTarget;

          return (
            <div key={measure.id} className="cem-card group transition-all duration-300">
              <div className="mb-4">
                <div className="flex justify-between items-start mb-1">
                  <h3 className="text-[10px] font-black text-slate-400 uppercase tracking-[0.2em]">{measure.name}</h3>
                  <div className="trend-pill trend-up">
                    <svg className="w-2.5 h-2.5" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="3" d="M5 15l7-7 7 7" /></svg>
                    2.4%
                  </div>
                </div>

                <div className="flex items-baseline gap-2 mb-4">
                  <span className="text-3xl font-bold text-slate-900 tracking-tight">{actual}</span>
                  <span className="text-xs text-slate-400 font-medium">/ {teamTarget} target</span>
                </div>

                {/* Cemdash Progress Bar */}
                <div className="cem-progress-container mb-3">
                  <div
                    className="cem-progress-bar transition-all duration-1000"
                    style={{
                      width: `${percent}%`,
                      backgroundColor: isWinning ? 'var(--success-color)' : 'var(--primary-color)'
                    }}
                  ></div>
                </div>

                <div className={`text-[10px] font-bold uppercase tracking-wider ${isWinning ? 'text-emerald-600' : 'text-rose-600'} flex items-center gap-1.5`}>
                  {isWinning ? (
                    <>
                      <div className="w-1.5 h-1.5 rounded-full bg-emerald-600"></div>
                      Target Achieved
                    </>
                  ) : (
                    <>
                      <div className="w-1.5 h-1.5 rounded-full bg-rose-600 animate-pulse"></div>
                      {teamTarget - actual} Needed
                    </>
                  )}
                </div>

              </div>
            </div>
          );
        })}
      </section>

      {/* SECTION B.4: TEAM VELOCITY & IMPACT (Correlation Chart) */}
      <section>
        <CorrelationChart
          tickets={tickets}
          commitments={commitments}
          currentWeekId={currentWeekId}
          wigConfig={wigConfig}
          currentWins={currentScore}
          lastTicketSync={lastTicketSync}
        />
      </section>

      {/* SECTION B.5: WEEKLY PROGRESS (Progress Over Time) - SLIM MODERN */}
      <section className="bg-white rounded-2xl p-6 shadow-soft border border-slate-100/60">
        <div className="flex justify-between items-center mb-4">
          <div>
            <h3 className="text-sm font-bold text-slate-900 uppercase tracking-wide">Weekly Momentum</h3>
          </div>
          <div className="flex gap-4 text-[10px] font-medium text-slate-400">
            <div className="flex items-center gap-1.5"><span className="w-2 h-2 rounded-full bg-brand-green"></span>Win</div>
            <div className="flex items-center gap-1.5"><span className="w-2 h-2 rounded-full bg-brand-red"></span>Miss</div>
          </div>
        </div>
        <div className="flex items-center gap-2 overflow-x-auto py-1">
          {(() => {
            // Build the last 6 weeks using the shared (WIG-day-aware) week IDs.
            const weeks: Array<{ weekId: string; completed: number; total: number; state: 'win' | 'miss' | 'live' | 'empty' }> = [];
            let weekId = currentWeekId;

            for (let i = 0; i < 6; i++) {
              const weekCommitments = (commitments as Commitment[]).filter((c: Commitment) => c.weekId === weekId);
              const completed = weekCommitments.filter((c: Commitment) => c.status === 'completed').length;
              const total = weekCommitments.length;
              const isCurrent = weekId === currentWeekId;
              let state: 'win' | 'miss' | 'live' | 'empty' = 'empty';
              if (total === 0) {
                state = 'empty';
              } else if (isCurrent) {
                state = 'live';
              } else {
                // A past week is a "win" if at least half the commitments were completed.
                state = completed >= Math.ceil(total / 2) ? 'win' : 'miss';
              }
              weeks.push({ weekId, completed, total, state });
              weekId = getPreviousWeekId(weekId);
            }

            const styles: Record<string, { bar: string; box: string; mark: string }> = {
              win: { bar: 'bg-brand-green', box: 'bg-brand-green/10 border-brand-green/20 text-brand-green', mark: '✓' },
              miss: { bar: 'bg-brand-red', box: 'bg-brand-red/10 border-brand-red/20 text-brand-red', mark: '✗' },
              live: { bar: 'bg-brand-orange', box: 'bg-brand-orange/10 border-brand-orange/20 text-brand-orange', mark: '•' },
              empty: { bar: 'bg-slate-100', box: 'bg-slate-50 border-slate-100 text-slate-300', mark: '—' },
            };

            return weeks.reverse().map((week, idx) => {
              const s = styles[week.state];
              return (
                <div key={week.weekId} className="flex flex-col items-center flex-1">
                  <div className={`w-full h-1.5 rounded-full mb-2 ${s.bar}`}></div>
                  <div className={`w-8 h-8 rounded-lg flex items-center justify-center font-bold text-xs border transition-all ${s.box}`}>
                    {s.mark}
                  </div>
                  <span className="text-[9px] font-semibold text-slate-400 mt-1 uppercase tracking-tight">
                    {idx === weeks.length - 1 ? 'Now' : `W${week.weekId.split('-W')[1]}`}
                  </span>
                </div>
              );
            });
          })()}
        </div>
      </section>
      {/* SECTION B.7: COMMITMENT LEADERBOARD (Gamified Per-Member Completed Counts) */}
      <section className="bg-white rounded-2xl shadow-soft border border-slate-100/60 overflow-hidden">
        <div className="p-6 border-b border-slate-50 flex justify-between items-center">
          <div>
            <h3 className="text-sm font-bold text-slate-900 uppercase tracking-wide flex items-center gap-2">
              <span className="text-xl">🏆</span> Commitment Leaderboard
            </h3>
            <p className="text-slate-400 text-[10px] font-medium uppercase tracking-wider mt-0.5">This Week vs All-Time Completed</p>
          </div>
          <div className="text-[10px] text-slate-400 font-medium bg-slate-50 px-2 py-1 rounded-lg">
            {commitmentLeaderboard.length} Players
          </div>
        </div>
        <div className="p-6 space-y-3">
          {commitmentLeaderboard.length === 0 ? (
            <p className="text-center text-slate-400 text-xs py-6">No data yet. Complete commitments to climb the leaderboard.</p>
          ) : (
            commitmentLeaderboard.map((entry, idx) => {
              const medals = ['🥇', '🥈', '🥉'];
              const medal = medals[idx];
              const maxAllTime = commitmentLeaderboard[0]?.allTime || 1;
              const pct = Math.min(100, (entry.allTime / maxAllTime) * 100);
              const isTop = idx === 0 && entry.allTime > 0;
              return (
                <div key={entry.memberId} className={`flex items-center gap-4 p-3 rounded-xl transition-all ${isTop ? 'bg-gradient-to-r from-yellow-50 to-transparent border border-yellow-200' : 'hover:bg-slate-50'}`}>
                  <div className="w-10 text-center text-xl font-black text-slate-400 shrink-0">
                    {medal || <span className="text-xs text-slate-300">#{idx + 1}</span>}
                  </div>
                  <div className="h-9 w-9 bg-slate-100 rounded-lg flex items-center justify-center font-bold text-slate-600 text-[10px] border border-slate-200 uppercase shrink-0">
                    {entry.avatar || (entry.name ? entry.name.substring(0, 2) : '??')}
                  </div>
                  <div className="flex-grow min-w-0">
                    <div className="flex justify-between items-center mb-1.5 gap-3 flex-wrap">
                      <span className="font-bold text-slate-700 text-sm truncate">{entry.name}</span>
                      <div className="flex items-center gap-2 text-[10px]">
                        <span className="bg-brand-navy/10 text-brand-navy px-2 py-0.5 rounded font-black uppercase tracking-wider">
                          Wk: {entry.thisWeek}
                        </span>
                        <span className="bg-brand-green/10 text-brand-green px-2 py-0.5 rounded font-black uppercase tracking-wider">
                          All-Time: {entry.allTime}
                        </span>
                        {entry.streak > 0 && (
                          <span className="text-orange-500 font-black flex items-center gap-0.5">
                            {entry.streak}<span className="text-[10px]">🔥</span>
                          </span>
                        )}
                      </div>
                    </div>
                    <div className="h-1.5 w-full bg-slate-100 rounded-full overflow-hidden">
                      <div
                        className={`h-full transition-all duration-1000 ${isTop ? 'bg-gradient-to-r from-yellow-400 to-orange-400' : 'bg-gradient-to-r from-brand-green to-brand-navy'}`}
                        style={{ width: `${pct}%` }}
                      ></div>
                    </div>
                  </div>
                </div>
              );
            })
          )}
        </div>
      </section>

      {/* SECTION C: THE PLAYER ROSTER (Accountability Grid - Read-Only Scores) */}
      <section className="bg-white rounded-2xl shadow-soft border border-slate-100/60 overflow-hidden">
        <div className="p-6 border-b border-slate-50 flex justify-between items-center">
          <div>
            <h3 className="text-sm font-bold text-slate-900 uppercase tracking-wide">Player Roster</h3>
            <p className="text-slate-400 text-[10px] font-medium uppercase tracking-wider mt-0.5">Accountability Grid</p>
          </div>
          <div className="text-[10px] text-slate-400 font-medium bg-slate-50 px-2 py-1 rounded-lg">
            Verified Weekly
          </div>
        </div>
        <div className="overflow-x-auto">
          <table className="w-full text-left">
            <thead>
              <tr className="bg-white text-[10px] font-bold uppercase text-slate-400 tracking-wider border-b border-slate-100">
                <th className="px-6 py-3 font-medium">Name</th>
                <th className="px-6 py-3 font-medium">Streak</th>
                <th className="px-6 py-3 font-medium">Score</th>
                {leadMeasures.map(measure => (
                  <th key={measure.id} className="px-6 py-3 font-medium">{measure.name}</th>
                ))}
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-50">
              {members.filter(m => m && m.name).map(member => (
                <tr key={member.id} className="hover:bg-slate-50/80 transition-colors group">
                  <td className="px-6 py-4">
                    <div className="flex items-center gap-3">
                      <div className="h-8 w-8 bg-slate-100 rounded-lg flex items-center justify-center font-bold text-slate-600 text-[10px] border border-slate-200 group-hover:border-brand-navy/30 group-hover:text-brand-navy transition-all uppercase">
                        {member.avatar || (member.name ? member.name.substring(0, 2) : '??')}
                      </div>
                      <span className="font-semibold text-slate-700 text-sm tracking-tight group-hover:text-slate-900">{member.name || 'Unknown'}</span>
                    </div>
                  </td>
                  <td className="px-6 py-4">
                    <div className="flex items-center gap-1.5">
                      <span className={`font-bold ${member.streak > 0 ? 'text-orange-500' : 'text-slate-300'}`}>
                        {member.streak || 0}
                      </span>
                      {member.streak > 0 && <span className="text-[10px]">🔥</span>}
                    </div>
                  </td>
                  <td className="px-6 py-4">
                    <span className="font-bold text-slate-600">{(member.score || 0).toLocaleString()}</span>
                  </td>
                  {leadMeasures.map((measure, measureIndex) => {
                    // Count this member's completed commitments
                    // Match by ID OR by name (some commitments store name in leadMeasureId)
                    const byLeadMeasure = currentWeekCommitments.filter(c =>
                      c.memberId === member.id &&
                      c.status === 'completed' &&
                      (c.leadMeasureId === measure.id ||
                        c.leadMeasureId === measure.name ||
                        c.leadMeasureName === measure.name)
                    ).length;

                    const memberTotalCompleted = currentWeekCommitments.filter(c =>
                      c.memberId === member.id && c.status === 'completed'
                    ).length;

                    const hasAnyWithLeadMeasure = currentWeekCommitments.some(c => c.leadMeasureId || c.leadMeasureName);

                    // Fall back to total if no leadMeasureId assigned
                    const currentCount = hasAnyWithLeadMeasure
                      ? byLeadMeasure
                      : (measureIndex === 0 ? memberTotalCompleted : 0);

                    const target = measure.target || 1;
                    const isOnTrack = currentCount >= target;
                    return (
                      <td key={measure.id} className="px-6 py-4">
                        <div className="flex items-center gap-2">
                          <span className={`text-sm font-bold ${isOnTrack ? 'text-brand-green' : 'text-slate-400'}`}>
                            {currentCount}
                          </span>
                          <span className="text-slate-300 text-[10px] font-medium">/ {target}</span>
                          {isOnTrack && (
                            <span className="bg-brand-green/10 text-brand-green text-[9px] px-1.5 py-0.5 rounded font-bold">OK</span>
                          )}
                        </div>
                      </td>
                    );
                  })}
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </section>
    </div>
  );
};

export default Dashboard;
